# syntax=docker/dockerfile:1.7
FROM cr.weaviate.io/semitechnologies/weaviate:1.28.4

LABEL org.opencontainers.image.title="the-copy-weaviate"
LABEL org.opencontainers.image.description="Weaviate runtime image for The Copy platform"

RUN addgroup --system --gid 1001 weaviate && \
    adduser --system --uid 1001 --ingroup weaviate weaviate
USER weaviate
