import { TaskType } from "@/services/agents/core/enums";

import type { BrainstormAgentCatalogItem } from "./catalog-types";

export const BRAINSTORM_AGENTS_PRIMARY: readonly BrainstormAgentCatalogItem[] =
  Object.freeze([
    {
      id: TaskType.ANALYSIS,
      name: "CritiqueArchitect AI",
      nameAr: "مهندس النقد",
      role: "التحليل النقدي المعماري",
      description:
        "وكيل التحليل النقدي المعماري: نظام هجين متعدد الوكلاء يدمج التفكير الجدلي مع التحليل الشعاعي العميق",
      category: "core",
      icon: "brain",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.INTEGRATED, TaskType.CHARACTER_DEEP_ANALYZER],
      enhances: [TaskType.RECOMMENDATIONS_GENERATOR],
      complexityScore: 0.95,
      phaseRelevance: [1, 3],
    },
    {
      id: TaskType.CREATIVE,
      name: "MimesisGen AI",
      nameAr: "مولّد المحاكاة",
      role: "المحاكاة التوليدية الإبداعية",
      description:
        "وكيل المحاكاة التوليدية الإبداعية: نظام ذكي متقدم يستخدم تقنيات نقل الأسلوب العصبي",
      category: "core",
      icon: "sparkles",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.INTEGRATED, TaskType.STYLE_FINGERPRINT],
      enhances: [TaskType.CHARACTER_VOICE, TaskType.SCENE_GENERATOR],
      complexityScore: 0.88,
      phaseRelevance: [2, 4],
    },
    {
      id: TaskType.INTEGRATED,
      name: "SynthesisOrchestrator AI",
      nameAr: "المنسق التركيبي",
      role: "التنسيق والتكامل",
      description:
        "المنسق التركيبي الذكي: وكيل أوركسترالي متقدم يستخدم تقنيات الذكاء الجمعي",
      category: "core",
      icon: "rocket",
      capabilities: {
        canAnalyze: true,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.ANALYSIS, TaskType.CREATIVE],
      enhances: [],
      complexityScore: 0.92,
      phaseRelevance: [4, 5],
    },
    {
      id: TaskType.COMPLETION,
      name: "NarrativeContinuum AI",
      nameAr: "مواصل السرد",
      role: "استكمال السرد",
      description:
        "وكيل استمرارية السرد الذكي: نظام تنبؤي متطور يستخدم نماذج الانتباه متعددة الرؤوس",
      category: "core",
      icon: "layers",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.STYLE_FINGERPRINT, TaskType.CHARACTER_VOICE],
      enhances: [],
      complexityScore: 0.85,
      phaseRelevance: [2, 5],
    },
    {
      id: TaskType.RHYTHM_MAPPING,
      name: "TemporalDynamics AI",
      nameAr: "محلل الإيقاع",
      role: "رسم الإيقاع الزمني",
      description:
        "وكيل ديناميكيات الإيقاع الزمني: محلل متطور يستخدم تقنيات معالجة الإشارات الرقمية",
      category: "analysis",
      icon: "music",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: false,
        usesSelfReflection: false,
        supportsRAG: false,
      },
      collaboratesWith: [TaskType.TENSION_OPTIMIZER],
      enhances: [TaskType.ANALYSIS],
      complexityScore: 0.75,
      phaseRelevance: [3],
    },
    {
      id: TaskType.CHARACTER_NETWORK,
      name: "SocialGraph AI",
      nameAr: "محلل الشبكات",
      role: "شبكات الشخصيات الاجتماعية",
      description:
        "وكيل شبكات الشخصيات الاجتماعية: محلل متقدم يطبق نظرية الرسوم البيانية",
      category: "analysis",
      icon: "users",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: false,
      },
      collaboratesWith: [TaskType.CHARACTER_DEEP_ANALYZER],
      enhances: [TaskType.CHARACTER_DEEP_ANALYZER],
      complexityScore: 0.8,
      phaseRelevance: [3],
    },
    {
      id: TaskType.DIALOGUE_FORENSICS,
      name: "Voiceprint AI",
      nameAr: "محلل البصمة الصوتية",
      role: "التحليل الجنائي للحوار",
      description:
        "وكيل البصمة الصوتية للحوار: محلل لغوي متطور يستخدم تقنيات NLP المتقدمة",
      category: "analysis",
      icon: "message-square",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.CHARACTER_VOICE,
        TaskType.DIALOGUE_ADVANCED_ANALYZER,
      ],
      enhances: [TaskType.CHARACTER_VOICE],
      complexityScore: 0.82,
      phaseRelevance: [3],
    },
    {
      id: TaskType.THEMATIC_MINING,
      name: "ConceptMiner AI",
      nameAr: "منقّب المفاهيم",
      role: "التنقيب المفاهيمي العميق",
      description:
        "وكيل التنقيب المفاهيمي العميق: محرك ذكي يستخدم تقنيات التعلم غير المراقب",
      category: "analysis",
      icon: "search",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.THEMES_MESSAGES_ANALYZER],
      enhances: [TaskType.THEMES_MESSAGES_ANALYZER],
      complexityScore: 0.88,
      phaseRelevance: [3],
    },
    {
      id: TaskType.STYLE_FINGERPRINT,
      name: "AuthorDNA AI",
      nameAr: "محلل البصمة الأدبية",
      role: "البصمة الأدبية للمؤلف",
      description:
        "وكيل الحمض النووي الأدبي: نظام تحليل أسلوبي متطور يستخدم تقنيات Stylometry",
      category: "analysis",
      icon: "fingerprint",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.CREATIVE, TaskType.CHARACTER_VOICE],
      enhances: [TaskType.CREATIVE, TaskType.CHARACTER_VOICE],
      complexityScore: 0.9,
      phaseRelevance: [1, 3],
    },
    {
      id: TaskType.CONFLICT_DYNAMICS,
      name: "TensionField AI",
      nameAr: "محلل حقول التوتر",
      role: "ديناميكيات الصراع",
      description:
        "وكيل حقول التوتر الدرامي: محلل ديناميكي متطور يطبق نظريات ميكانيكا الموائع",
      category: "analysis",
      icon: "zap",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: false,
      },
      collaboratesWith: [TaskType.TENSION_OPTIMIZER],
      enhances: [TaskType.TENSION_OPTIMIZER],
      complexityScore: 0.85,
      phaseRelevance: [3],
    },
    {
      id: TaskType.ADAPTIVE_REWRITING,
      name: "ContextTransformer AI",
      nameAr: "محوّل السياق",
      role: "إعادة الكتابة التكيفية",
      description:
        "وكيل التحويل السياقي التكيفي: نظام إعادة صياغة متقدم يعتمد على بنية Transformer",
      category: "creative",
      icon: "pen-tool",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.PLATFORM_ADAPTER,
        TaskType.TARGET_AUDIENCE_ANALYZER,
        TaskType.STYLE_FINGERPRINT,
      ],
      enhances: [TaskType.PLATFORM_ADAPTER],
      complexityScore: 0.82,
      phaseRelevance: [4, 5],
    },
    {
      id: TaskType.SCENE_GENERATOR,
      name: "SceneArchitect AI",
      nameAr: "معمار المشاهد",
      role: "توليد المشاهد الدرامية",
      description:
        "وكيل معمار المشاهد الذكي: مولد مشاهد متطور يستخدم تقنيات التخطيط الهرمي",
      category: "creative",
      icon: "file-text",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.CHARACTER_VOICE],
      enhances: [],
      complexityScore: 0.8,
      phaseRelevance: [2, 4],
    },
    {
      id: TaskType.CHARACTER_VOICE,
      name: "PersonaSynth AI",
      nameAr: "مركّب الشخصيات",
      role: "تركيب صوت الشخصية",
      description:
        "وكيل تركيب الشخصيات الصوتية: محرك متطور لمحاكاة الأصوات الشخصية",
      category: "creative",
      icon: "users",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.DIALOGUE_FORENSICS, TaskType.SCENE_GENERATOR],
      enhances: [TaskType.SCENE_GENERATOR],
      complexityScore: 0.85,
      phaseRelevance: [2, 4],
    },
    {
      id: TaskType.WORLD_BUILDER,
      name: "CosmosForge AI",
      nameAr: "حدّاد الأكوان",
      role: "بناء العوالم الدرامية",
      description:
        "وكيل حدادة الأكوان الدرامية: بانٍ عوالم متطور يستخدم تقنيات الذكاء الاصطناعي التوليدي",
      category: "creative",
      icon: "globe",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.CULTURAL_HISTORICAL_ANALYZER],
      enhances: [],
      complexityScore: 0.9,
      phaseRelevance: [2],
    },
  ]);
