import { TaskType } from "@/services/agents/core/enums";

import type { BrainstormAgentCatalogItem } from "./catalog-types";

export const BRAINSTORM_AGENTS_SECONDARY: readonly BrainstormAgentCatalogItem[] =
  Object.freeze([
    {
      id: TaskType.PLOT_PREDICTOR,
      name: "NarrativeOracle AI",
      nameAr: "عرّاف الحبكة",
      role: "التنبؤ بمسار الحبكة",
      description:
        "وكيل الوحي السردي: متنبئ حبكة متطور يستخدم نماذج Transformer المتخصصة",
      category: "predictive",
      icon: "compass",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.TENSION_OPTIMIZER],
      enhances: [TaskType.COMPLETION],
      complexityScore: 0.88,
      phaseRelevance: [2, 4],
    },
    {
      id: TaskType.TENSION_OPTIMIZER,
      name: "DramaEngine AI",
      nameAr: "محرك الدراما",
      role: "تحسين التوتر الدرامي",
      description:
        "وكيل محرك الدراما التحسيني: محسن توتر متطور يستخدم خوارزميات التحسين التطورية",
      category: "predictive",
      icon: "zap",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: false,
      },
      collaboratesWith: [TaskType.RHYTHM_MAPPING, TaskType.AUDIENCE_RESONANCE],
      enhances: [],
      complexityScore: 0.82,
      phaseRelevance: [3, 4],
    },
    {
      id: TaskType.AUDIENCE_RESONANCE,
      name: "EmpathyMatrix AI",
      nameAr: "مصفوفة التعاطف",
      role: "صدى الجمهور العاطفي",
      description:
        "وكيل مصفوفة التعاطف الجماهيري: محلل صدى متطور يستخدم نماذج علم النفس الجماعي",
      category: "predictive",
      icon: "target",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.TARGET_AUDIENCE_ANALYZER],
      enhances: [TaskType.TARGET_AUDIENCE_ANALYZER],
      complexityScore: 0.8,
      phaseRelevance: [3, 5],
    },
    {
      id: TaskType.PLATFORM_ADAPTER,
      name: "MediaTransmorph AI",
      nameAr: "محوّل المنصات",
      role: "التكيف مع المنصات",
      description:
        "وكيل التحويل الإعلامي المتعدد: محول منصات ذكي يستخدم تقنيات التحليل الوسائطي",
      category: "predictive",
      icon: "layers",
      capabilities: {
        canAnalyze: false,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.ADAPTIVE_REWRITING],
      enhances: [],
      complexityScore: 0.75,
      phaseRelevance: [5],
    },
    {
      id: TaskType.CHARACTER_DEEP_ANALYZER,
      name: "PsycheScope AI",
      nameAr: "مجهر النفسية",
      role: "التحليل النفسي العميق",
      description:
        "الوحدة 3 - مجهر النفسية العميقة: محلل شخصيات متقدم يستخدم نماذج علم النفس الحاسوبي",
      category: "advanced",
      icon: "brain",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.CHARACTER_NETWORK, TaskType.CHARACTER_VOICE],
      enhances: [TaskType.CHARACTER_VOICE],
      complexityScore: 0.92,
      phaseRelevance: [3],
    },
    {
      id: TaskType.DIALOGUE_ADVANCED_ANALYZER,
      name: "ConversationLens AI",
      nameAr: "عدسة المحادثة",
      role: "التحليل المتقدم للحوار",
      description:
        "الوحدة 4 - عدسة المحادثة المتقدمة: محلل حوار متطور يستخدم تقنيات اللسانيات الحاسوبية",
      category: "advanced",
      icon: "message-square",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.DIALOGUE_FORENSICS],
      enhances: [TaskType.CHARACTER_VOICE],
      complexityScore: 0.85,
      phaseRelevance: [3],
    },
    {
      id: TaskType.VISUAL_CINEMATIC_ANALYZER,
      name: "CinemaVision AI",
      nameAr: "بصيرة السينما",
      role: "التحليل السينمائي البصري",
      description: "الوحدة 5 - بصيرة السينما الذكية: محلل بصري سينمائي متطور",
      category: "advanced",
      icon: "film",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: false,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.PRODUCIBILITY_ANALYZER],
      enhances: [TaskType.PRODUCIBILITY_ANALYZER],
      complexityScore: 0.8,
      phaseRelevance: [3],
    },
    {
      id: TaskType.THEMES_MESSAGES_ANALYZER,
      name: "PhilosophyMiner AI",
      nameAr: "منقّب الفلسفة",
      role: "تحليل المواضيع والرسائل",
      description: "الوحدة 6 - منقب الفلسفة العميقة: محلل موضوعات ورسائل متطور",
      category: "advanced",
      icon: "book-open",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.THEMATIC_MINING,
        TaskType.CULTURAL_HISTORICAL_ANALYZER,
      ],
      enhances: [TaskType.LITERARY_QUALITY_ANALYZER],
      complexityScore: 0.95,
      phaseRelevance: [3],
    },
    {
      id: TaskType.CULTURAL_HISTORICAL_ANALYZER,
      name: "ChronoContext AI",
      nameAr: "سياق الزمن",
      role: "التحليل الثقافي التاريخي",
      description:
        "الوحدة 7 - سياق الزمن الثقافي: محلل سياق ثقافي تاريخي متطور",
      category: "advanced",
      icon: "globe",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.WORLD_BUILDER,
        TaskType.TARGET_AUDIENCE_ANALYZER,
      ],
      enhances: [TaskType.WORLD_BUILDER],
      complexityScore: 0.88,
      phaseRelevance: [1, 3],
    },
    {
      id: TaskType.PRODUCIBILITY_ANALYZER,
      name: "ProductionOracle AI",
      nameAr: "وحي الإنتاج",
      role: "تحليل قابلية الإنتاج",
      description: "الوحدة 8 - وحي الإنتاج الذكي: محلل قابلية إنتاج متطور",
      category: "advanced",
      icon: "chart-bar",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.VISUAL_CINEMATIC_ANALYZER],
      enhances: [],
      complexityScore: 0.78,
      phaseRelevance: [5],
    },
    {
      id: TaskType.TARGET_AUDIENCE_ANALYZER,
      name: "AudienceCompass AI",
      nameAr: "بوصلة الجمهور",
      role: "تحليل الجمهور المستهدف",
      description: "الوحدة 9 - بوصلة الجمهور الذكية: محلل جمهور مستهدف متطور",
      category: "advanced",
      icon: "compass",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.AUDIENCE_RESONANCE,
        TaskType.CULTURAL_HISTORICAL_ANALYZER,
      ],
      enhances: [TaskType.AUDIENCE_RESONANCE],
      complexityScore: 0.82,
      phaseRelevance: [1, 5],
    },
    {
      id: TaskType.LITERARY_QUALITY_ANALYZER,
      name: "AestheticsJudge AI",
      nameAr: "قاضي الجماليات",
      role: "تحليل الجودة الأدبية",
      description: "الوحدة 10 - قاضي الجماليات الأدبية: محلل جودة أدبية متطور",
      category: "advanced",
      icon: "trophy",
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.STYLE_FINGERPRINT,
        TaskType.THEMES_MESSAGES_ANALYZER,
      ],
      enhances: [],
      complexityScore: 0.9,
      phaseRelevance: [3, 5],
    },
    {
      id: TaskType.RECOMMENDATIONS_GENERATOR,
      name: "WisdomSynthesizer AI",
      nameAr: "مركّب الحكمة",
      role: "توليد التوصيات والتحسينات",
      description:
        "الوحدة 11 - مُركب الحكمة الإبداعية: مولد توصيات وتحسينات متطور",
      category: "advanced",
      icon: "lightbulb",
      capabilities: {
        canAnalyze: true,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.ANALYSIS, TaskType.LITERARY_QUALITY_ANALYZER],
      enhances: [],
      complexityScore: 0.88,
      phaseRelevance: [5],
    },
  ]);
