import type { KnowledgeSystemDefinition } from "./types";
import { RAG_CONTRACT_PATH } from "../constants";

export const KNOWLEDGE_DISCOVERY_EXCLUDED_FILE_PATTERNS = [
  "dop_assistant_spec_package/",
  "arab-stylist-studio-spec/",
  "scripts/lint-chunked.mjs",
  "scripts/run-vitest-chunks.mjs",
];

export const KNOWLEDGE_SYSTEM_DEFINITIONS: KnowledgeSystemDefinition[] = [
  {
    id: "workspace-embeddings",
    label: "Workspace Code Embeddings",
    category: "code-retrieval",
    policy: "govern-only",
    root: "scripts",
    description:
      "Live agent code memory with LanceDB local storage and optional Qdrant sync.",
    commands: [
      "pnpm workspace:embed",
      "pnpm agent:memory:index",
      "pnpm agent:memory:search",
      "pnpm agent:memory:status",
      "pnpm agent:memory:verify",
      "pnpm agent:memory:watch",
      "pnpm agent:guard:step",
    ],
    entrypoints: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/guard.ts",
      "scripts/agent/code-memory-index.ts",
      "scripts/agent/code-memory-search.ts",
      "scripts/agent/code-memory-status.ts",
      "scripts/agent/code-memory-verify.ts",
      "scripts/agent/code-memory-watch.ts",
    ],
    criticalFiles: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/guard.ts",
      "scripts/agent/code-memory-index.ts",
      "scripts/agent/code-memory-search.ts",
      "scripts/agent/code-memory-status.ts",
      "scripts/agent/code-memory-verify.ts",
      "scripts/agent/code-memory-watch.ts",
      "scripts/agent/lib/agent-guard.ts",
      "scripts/agent/lib/code-memory/config.ts",
      "scripts/agent/lib/code-memory/discovery.ts",
      "scripts/agent/lib/code-memory/embedder.ts",
      "scripts/agent/lib/code-memory/store.ts",
      "scripts/agent/lib/code-memory/qdrant.ts",
      "scripts/agent/lib/code-memory/status.ts",
      "scripts/agent/lib/code-memory/commands.ts",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
      ".agent-code-memory/manifest.json",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "package.json",
      "pnpm-workspace.yaml",
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/lib/code-memory/*",
      "apps/*",
      "packages/*",
    ],
    artifacts: [
      ".agent-code-memory/",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
    ],
    dependencies: [
      "OpenRouter embeddings",
      "LanceDB",
      "Qdrant",
      "pnpm workspace:embed",
    ],
    components: [
      { kind: "entrypoint", path: "scripts/generate-workspace-embeddings.js" },
      { kind: "entrypoint", path: "scripts/agent/guard.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-index.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-search.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-status.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-verify.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-watch.ts" },
      { kind: "chunking", path: "scripts/agent/lib/code-memory/discovery.ts" },
      {
        kind: "embedding-generation",
        path: "scripts/agent/lib/code-memory/embedder.ts",
      },
      { kind: "indexing", path: "scripts/agent/lib/code-memory/store.ts" },
      { kind: "vector-store", path: "scripts/agent/lib/code-memory/store.ts" },
      { kind: "vector-store", path: "scripts/agent/lib/code-memory/qdrant.ts" },
      { kind: "search", path: "scripts/agent/lib/code-memory/commands.ts" },
      { kind: "governance", path: "scripts/agent/lib/agent-guard.ts" },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/code-memory-",
      "scripts/agent/lib/code-memory/",
      ".agent-code-memory/",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
    ],
    localDocPaths: [],
    providerPatterns: ["OpenRouter", "OPENROUTER_API_KEY"],
    vectorStorePatterns: [
      "LanceDB",
      "lancedb",
      "Qdrant",
      "qdrant",
      "WORKSPACE-EMBEDDING-INDEX.json",
      ".agent-code-memory",
    ],
    rerankerPatterns: [],
    allowMultipleVectorStores: true,
  },
  {
    id: "backend-memory",
    label: "Backend Memory Retrieval",
    category: "vector-memory",
    policy: "unify-now",
    root: "apps/backend/src/memory",
    description:
      "Unified repository indexing, Weaviate retrieval, and profile-based context assembly.",
    commands: [],
    entrypoints: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
    ],
    criticalFiles: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
      "apps/backend/src/memory/embeddings/generator.ts",
      "apps/backend/src/memory/embeddings/mrl-optimizer.ts",
      "apps/backend/src/memory/indexer/repository-crawler.ts",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/indexer/git-watcher.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
      "apps/backend/src/memory/retrieval/context-builder.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/vector-store/client.ts",
      "apps/backend/src/memory/vector-store/schema.ts",
      "apps/backend/src/memory/types.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "packages/core-memory/src/types.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
    ],
    artifacts: [
      "Weaviate:CodeChunks",
      "Weaviate:Documentation",
      "Weaviate:Decisions",
      "Weaviate:Architecture",
      "Weaviate:AdHocChunks",
    ],
    dependencies: [
      "Weaviate",
      "Google Gemini embeddings",
      "@the-copy/core-memory",
    ],
    components: [
      { kind: "entrypoint", path: "apps/backend/src/memory/index.ts" },
      { kind: "api", path: "apps/backend/src/memory/api/routes.ts" },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/memory/embeddings/generator.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/memory/embeddings/mrl-optimizer.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/repository-crawler.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/git-watcher.ts",
      },
      {
        kind: "chunking",
        path: "packages/core-memory/src/chunking/semanticChunker.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/context/context-assembly.service.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/retrieval/context-builder.ts",
      },
      {
        kind: "retrieval",
        path: "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/client.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/schema.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: ["apps/backend/src/memory/", "packages/core-memory/"],
    localDocPaths: [],
    providerPatterns: [
      "GoogleGenAI",
      "gemini-embedding-2",
      "gemini-embedding-001",
    ],
    vectorStorePatterns: [
      "weaviate",
      "Weaviate",
      "CodeChunks",
      "Documentation",
      "Decisions",
      "Architecture",
      "AdHocChunks",
    ],
    rerankerPatterns: ["selectHits"],
  },
  {
    id: "backend-enhanced-rag",
    label: "Backend Enhanced RAG",
    category: "drama-retrieval",
    policy: "unify-now",
    root: "apps/backend/src/services/rag",
    description:
      "Coordinator facade over shared chunking, Weaviate retrieval, and unified context assembly.",
    commands: [],
    entrypoints: ["apps/backend/src/services/rag/enhancedRAG.service.ts"],
    criticalFiles: [
      "apps/backend/src/services/rag/enhancedRAG.service.ts",
      "apps/backend/src/services/rag/embeddings.service.ts",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
      "apps/backend/src/memory/embeddings/generator.ts",
      "apps/backend/src/memory/vector-store/client.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "packages/core-memory/src/types.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/backend/src/services/rag/enhancedRAG.service.ts",
      "apps/backend/src/services/rag/embeddings.service.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
    ],
    artifacts: ["Weaviate:AdHocChunks", "ContextAssemblyService output"],
    dependencies: [
      "Weaviate",
      "ContextAssemblyService",
      "Google Gemini embeddings",
    ],
    components: [
      {
        kind: "entrypoint",
        path: "apps/backend/src/services/rag/enhancedRAG.service.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/services/rag/embeddings.service.ts",
      },
      {
        kind: "chunking",
        path: "packages/core-memory/src/chunking/semanticChunker.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      },
      {
        kind: "retrieval",
        path: "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/client.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/context/context-assembly.service.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: ["apps/backend/src/services/rag/"],
    localDocPaths: [],
    providerPatterns: [
      "GoogleGenAI",
      "GoogleGenerativeAI",
      "gemini-embedding-2",
      "gemini-embedding-001",
    ],
    vectorStorePatterns: [
      "weaviate",
      "Weaviate",
      "weaviateStore",
      "AdHocChunks",
    ],
    rerankerPatterns: ["selectHits"],
  },
  {
    id: "editor-code-rag",
    label: "Editor Code RAG",
    category: "code-retrieval",
    policy: "unify-now",
    root: "apps/backend/src/modules/editor-rag",
    description:
      "Backend-owned editor code retrieval over the unified Weaviate memory store with Gemini embeddings and answers.",
    commands: [
      "pnpm --filter @the-copy/backend editor-rag:index",
      "pnpm --filter @the-copy/backend editor-rag:ask",
      "pnpm --filter @the-copy/backend editor-rag:stats",
      "pnpm --filter @the-copy/backend editor-rag:smoke",
    ],
    entrypoints: [
      "apps/backend/src/modules/editor-rag/cli.ts",
      "apps/backend/src/modules/editor-rag/routes.ts",
      "apps/backend/src/modules/editor-rag/service.ts",
    ],
    criticalFiles: [
      "apps/backend/src/modules/editor-rag/cli.ts",
      "apps/backend/src/modules/editor-rag/routes.ts",
      "apps/backend/src/modules/editor-rag/service.ts",
      "apps/backend/src/memory/embeddings/generator.ts",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/retrieval/context-builder.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/vector-store/client.ts",
      "apps/backend/package.json",
      "apps/web/package.json",
      "apps/web/src/app/(main)/editor/src/rag/README.md",
      "apps/web/src/app/(main)/editor/src/rag/rag-system.md",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/backend/src/modules/editor-rag/*",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/retrieval/context-builder.ts",
      "apps/web/package.json",
      "apps/web/src/app/(main)/editor/src/**/*",
    ],
    artifacts: ["Weaviate:CodeChunks"],
    dependencies: [
      "Weaviate",
      "WEAVIATE_URL",
      "WEAVIATE_API_KEY",
      "GEMINI_API_KEY",
      "GOOGLE_GENAI_API_KEY",
      "gemini-embedding-2",
      "gemini-2.5-flash",
    ],
    components: [
      {
        kind: "entrypoint",
        path: "apps/backend/src/modules/editor-rag/cli.ts",
      },
      {
        kind: "api",
        path: "apps/backend/src/modules/editor-rag/routes.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/modules/editor-rag/service.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/memory/embeddings/generator.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      },
      {
        kind: "retrieval",
        path: "apps/backend/src/memory/retrieval/context-builder.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/client.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "apps/backend/src/modules/editor-rag/",
      "apps/web/src/app/(main)/editor/src/rag/",
    ],
    localDocPaths: [
      "apps/web/src/app/(main)/editor/src/rag/README.md",
      "apps/web/src/app/(main)/editor/src/rag/rag-system.md",
    ],
    providerPatterns: [
      "GoogleGenAI",
      "GEMINI_API_KEY",
      "GOOGLE_GENAI_API_KEY",
      "gemini-embedding-2",
      "gemini-2.5-flash",
    ],
    vectorStorePatterns: ["weaviate", "Weaviate", "CodeChunks"],
    rerankerPatterns: [],
    allowMultipleProviders: true,
  },
  {
    id: "persistent-agent-memory",
    label: "Persistent Agent Memory",
    category: "hybrid-knowledge",
    policy: "unify-now",
    root: "scripts/agent/lib/persistent-memory",
    description:
      "Durable governed agent-thread memory with PostgreSQL source of truth, Redis/BullMQ job handoff, vector index adapters, safe retrieval, and guarded context injection.",
    commands: [
      "pnpm agent:persistent-memory:secrets:scan",
      "pnpm agent:persistent-memory:secrets:verify",
      "pnpm agent:persistent-memory:secrets:purge",
      "pnpm agent:persistent-memory:init",
      "pnpm agent:persistent-memory:migrate",
      "pnpm agent:persistent-memory:index",
      "pnpm agent:persistent-memory:watch",
      "pnpm agent:persistent-memory:search",
      "pnpm agent:persistent-memory:ingest",
      "pnpm agent:persistent-memory:retrieve",
      "pnpm agent:persistent-memory:workers",
      "pnpm agent:persistent-memory:status",
      "pnpm agent:persistent-memory:eval",
      "pnpm agent:persistent-memory:eval:golden",
      "pnpm agent:persistent-memory:eval:safety",
    ],
    entrypoints: [
      "scripts/agent/persistent-memory-secrets.ts",
      "scripts/agent/persistent-memory-init.ts",
      "scripts/agent/persistent-memory-migrate.ts",
      "scripts/agent/persistent-memory-index.ts",
      "scripts/agent/persistent-memory-watch.ts",
      "scripts/agent/persistent-memory-search.ts",
      "scripts/agent/persistent-memory-ingest.ts",
      "scripts/agent/persistent-memory-retrieve.ts",
      "scripts/agent/persistent-memory-workers.ts",
      "scripts/agent/persistent-memory-status.ts",
      "scripts/agent/persistent-memory-eval.ts",
      "scripts/agent/lib/persistent-memory/index.ts",
    ],
    criticalFiles: [
      "apps/backend/src/db/persistent-agent-memory.schema.ts",
      "scripts/agent/persistent-memory-secrets.ts",
      "scripts/agent/persistent-memory-init.ts",
      "scripts/agent/persistent-memory-migrate.ts",
      "scripts/agent/persistent-memory-index.ts",
      "scripts/agent/persistent-memory-watch.ts",
      "scripts/agent/persistent-memory-search.ts",
      "scripts/agent/persistent-memory-ingest.ts",
      "scripts/agent/persistent-memory-retrieve.ts",
      "scripts/agent/persistent-memory-workers.ts",
      "scripts/agent/persistent-memory-status.ts",
      "scripts/agent/persistent-memory-eval.ts",
      "scripts/agent/lib/persistent-memory/index.ts",
      "scripts/agent/lib/persistent-memory/embeddings.ts",
      "scripts/agent/lib/persistent-memory/metrics.ts",
      "scripts/agent/lib/persistent-memory/budgets.ts",
      "scripts/agent/lib/persistent-memory/types.ts",
      "scripts/agent/lib/persistent-memory/secrets.ts",
      "scripts/agent/lib/persistent-memory/store.ts",
      "scripts/agent/lib/persistent-memory/postgres-store.ts",
      "scripts/agent/lib/persistent-memory/vector-index.ts",
      "scripts/agent/lib/persistent-memory/injection.ts",
      "scripts/agent/lib/persistent-memory/shadow-index.ts",
      "scripts/agent/lib/persistent-memory/startup-context.ts",
      "scripts/agent/lib/persistent-memory/runtime.ts",
      "scripts/agent/lib/persistent-memory/infra.ts",
      "scripts/agent/lib/persistent-memory/embedding.ts",
      "scripts/agent/lib/persistent-memory/persistent-memory.test.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "output/session-state.md",
      "output/round-notes.md",
      "AGENTS.md",
      "apps/backend/src/db/persistent-agent-memory.schema.ts",
      "scripts/agent/lib/persistent-memory/*",
    ],
    artifacts: [
      "PostgreSQL:persistent_agent_memory",
      "Weaviate:persistent-agent-memory-primary",
      "Qdrant:persistent-agent-memory-shadow",
      "Redis:bullmq-persistent-memory-jobs",
    ],
    dependencies: [
      "PostgreSQL",
      "Redis",
      "BullMQ",
      "Weaviate",
      "Qdrant",
      "local deterministic embeddings",
      "BAAI/bge-m3",
    ],
    components: [
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-secrets.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-init.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-migrate.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-index.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-watch.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-search.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-ingest.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-retrieve.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-workers.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-status.ts",
      },
      {
        kind: "entrypoint",
        path: "scripts/agent/persistent-memory-eval.ts",
      },
      {
        kind: "indexing",
        path: "scripts/agent/lib/persistent-memory/index.ts",
      },
      {
        kind: "embedding-generation",
        path: "scripts/agent/lib/persistent-memory/embeddings.ts",
      },
      {
        kind: "context-assembly",
        path: "scripts/agent/lib/persistent-memory/budgets.ts",
      },
      {
        kind: "governance",
        path: "scripts/agent/lib/persistent-memory/metrics.ts",
      },
      {
        kind: "vector-store",
        path: "scripts/agent/lib/persistent-memory/vector-index.ts",
      },
      {
        kind: "vector-store",
        path: "scripts/agent/lib/persistent-memory/shadow-index.ts",
      },
      {
        kind: "retrieval",
        path: "scripts/agent/lib/persistent-memory/index.ts",
      },
      {
        kind: "context-assembly",
        path: "scripts/agent/lib/persistent-memory/injection.ts",
      },
      {
        kind: "context-assembly",
        path: "scripts/agent/lib/persistent-memory/startup-context.ts",
      },
      {
        kind: "embedding-generation",
        path: "scripts/agent/lib/persistent-memory/embedding.ts",
      },
      {
        kind: "governance",
        path: "scripts/agent/lib/persistent-memory/secrets.ts",
      },
      {
        kind: "governance",
        path: RAG_CONTRACT_PATH,
      },
    ],
    ownedPrefixes: [
      "apps/backend/src/db/persistent-agent-memory.schema.ts",
      "scripts/agent/persistent-memory-",
      "scripts/agent/lib/persistent-memory/",
    ],
    localDocPaths: [],
    providerPatterns: ["local deterministic embeddings", "BAAI/bge-m3"],
    vectorStorePatterns: ["Weaviate", "Qdrant"],
    rerankerPatterns: ["ConditionalReranker"],
    allowMultipleVectorStores: true,
  },
  {
    id: "web-legacy-rag",
    label: "Web Legacy RAG Utilities",
    category: "lightweight-search",
    policy: "do-not-force-merge",
    root: "apps/web/src/lib",
    description:
      "Legacy in-web chunking and retrieval helpers retained under governance without forced architectural merge.",
    commands: [],
    entrypoints: [
      "apps/web/src/lib/ai/rag/index.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    criticalFiles: [
      "apps/web/src/lib/ai/stations/gemini-service.ts",
      "apps/web/src/lib/ai/rag/context-retriever.ts",
      "apps/web/src/lib/ai/rag/index.ts",
      "apps/web/src/lib/ai/rag/text-chunking.ts",
      "apps/web/src/lib/ai/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/web/src/lib/ai/rag/context-retriever.ts",
      "apps/web/src/lib/ai/rag/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    artifacts: ["In-memory context maps", "In-memory retrieved chunks"],
    dependencies: ["GeminiService", "Frontend in-memory chunking"],
    components: [
      { kind: "entrypoint", path: "apps/web/src/lib/ai/rag/index.ts" },
      { kind: "chunking", path: "apps/web/src/lib/ai/rag/text-chunking.ts" },
      { kind: "chunking", path: "apps/web/src/lib/ai/text-chunking.ts" },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/ai/rag/context-retriever.ts",
      },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/drama-analyst/services/ragService.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/web/src/lib/ai/stations/gemini-service.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "apps/web/src/lib/ai/rag/",
      "apps/web/src/lib/ai/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    localDocPaths: [],
    providerPatterns: ["GeminiService", "geminiService"],
    vectorStorePatterns: [],
    rerankerPatterns: [],
  },
];
