interface ExportFileNameInput {
  actorName: string;
  projectName: string;
  roleName: string;
  takeName: string;
  extension: string;
}

interface TakeInsightsInput {
  durationSeconds: number;
  scriptText: string;
  teleprompterUsed: boolean;
  hadRetake: boolean;
}

interface PersistedTakeNote {
  id: string;
  timestamp: number;
  type: "emotion" | "delivery" | "timing" | "movement" | "improvement";
  content: string;
  severity: "positive" | "neutral" | "needs_work";
  autoGenerated: boolean;
}

export interface PersistedSelfTapeTake {
  id: string;
  name: string;
  duration: number;
  recordedAt: string;
  notes: PersistedTakeNote[];
  score?: number;
  status: "recording" | "completed" | "exported";
  mimeType?: string;
  source: "sample" | "captured";
}

export interface TakeInsightNote {
  type: "timing" | "delivery" | "improvement";
  severity: "positive" | "neutral" | "needs_work";
  content: string;
}

export interface TakeInsights {
  score: number;
  notes: TakeInsightNote[];
}

export const SELF_TAPE_STORAGE_KEY = "actorai-arabic:self-tape-suite";

const ARABIC_TO_LATIN: Record<string, string> = {
  ا: "a",
  أ: "a",
  إ: "i",
  آ: "a",
  ب: "b",
  ت: "t",
  ث: "th",
  ج: "j",
  ح: "h",
  خ: "kh",
  د: "d",
  ذ: "dh",
  ر: "r",
  ز: "z",
  س: "s",
  ش: "sh",
  ص: "s",
  ض: "d",
  ط: "t",
  ظ: "z",
  ع: "a",
  غ: "gh",
  ف: "f",
  ق: "q",
  ك: "k",
  ل: "l",
  م: "m",
  ن: "n",
  ه: "h",
  و: "w",
  ي: "i",
  ى: "a",
  ة: "a",
};

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function transliterateToSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .split("")
    .map((char) => {
      if (ARABIC_TO_LATIN[char]) {
        return ARABIC_TO_LATIN[char];
      }

      if (/[a-z0-9]/.test(char)) {
        return char;
      }

      if (/\s|-|_/.test(char)) {
        return "-";
      }

      return "";
    })
    .join("")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function pickSupportedMimeType(candidates: string[]): string {
  if (typeof MediaRecorder === "undefined") {
    return candidates[0] ?? "video/webm";
  }

  return (
    candidates.find((candidate) => MediaRecorder.isTypeSupported(candidate)) ??
    candidates[candidates.length - 1] ??
    "video/webm"
  );
}

export function inferExtensionFromMimeType(mimeType?: string): string {
  if (!mimeType) {
    return "webm";
  }

  if (mimeType.includes("mp4")) {
    return "mp4";
  }

  if (mimeType.includes("quicktime") || mimeType.includes("mov")) {
    return "mov";
  }

  return "webm";
}

export function supportsMediaCapture(): boolean {
  return Boolean(
    typeof navigator !== "undefined" &&
    typeof navigator.mediaDevices?.getUserMedia === "function" &&
    typeof MediaRecorder !== "undefined"
  );
}

function isPersistedTakeNote(value: unknown): value is PersistedTakeNote {
  if (!value || typeof value !== "object") {
    return false;
  }

  const note = value as Partial<PersistedTakeNote>;
  return (
    typeof note.id === "string" &&
    typeof note.timestamp === "number" &&
    typeof note.type === "string" &&
    typeof note.content === "string" &&
    typeof note.severity === "string" &&
    typeof note.autoGenerated === "boolean"
  );
}

function isPersistedTake(value: unknown): value is PersistedSelfTapeTake {
  if (!value || typeof value !== "object") {
    return false;
  }

  const take = value as Partial<PersistedSelfTapeTake>;
  return (
    typeof take.id === "string" &&
    typeof take.name === "string" &&
    typeof take.duration === "number" &&
    typeof take.recordedAt === "string" &&
    Array.isArray(take.notes) &&
    take.notes.every(isPersistedTakeNote) &&
    typeof take.status === "string" &&
    typeof take.source === "string"
  );
}

export function readStoredSelfTapeTakes(
  fallback: PersistedSelfTapeTake[]
): PersistedSelfTapeTake[] {
  if (typeof window === "undefined") {
    return fallback;
  }

  const raw = window.localStorage.getItem(SELF_TAPE_STORAGE_KEY);
  if (!raw) {
    return fallback;
  }

  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) {
      return fallback;
    }

    const validTakes = parsed.filter(isPersistedTake);
    return validTakes.length > 0 ? validTakes : fallback;
  } catch {
    return fallback;
  }
}

export function writeStoredSelfTapeTakes(takes: PersistedSelfTapeTake[]): void {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.setItem(SELF_TAPE_STORAGE_KEY, JSON.stringify(takes));
}

export function buildExportFileName(input: ExportFileNameInput): string {
  const segments = [
    input.actorName,
    input.projectName,
    input.roleName,
    input.takeName,
  ]
    .map(transliterateToSlug)
    .filter(Boolean);

  return `${segments.join("-")}.${input.extension.replace(/^\./, "")}`;
}

export function buildTakeInsights(input: TakeInsightsInput): TakeInsights {
  const scriptWordCount = input.scriptText.split(/\s+/).filter(Boolean).length;
  const expectedDuration = Math.max(45, Math.round(scriptWordCount * 1.2));
  const durationDelta = Math.abs(input.durationSeconds - expectedDuration);
  const timingScore = clamp(100 - durationDelta, 35, 100);
  const supportScore = input.teleprompterUsed ? 6 : 10;
  const retakePenalty = input.hadRetake ? 6 : 0;
  const score = clamp(
    Math.round(timingScore * 0.8 + supportScore * 2 - retakePenalty),
    0,
    100
  );

  const notes: TakeInsightNote[] = [
    timingScore > 80
      ? {
          type: "timing",
          severity: "positive",
          content:
            "المدة قريبة من الإيقاع المتوقع للنص، وهذا يدعم قابلية المشاهدة.",
        }
      : {
          type: "timing",
          severity: "needs_work",
          content:
            "المدة خرجت عن الإيقاع المتوقع للنص، ويستحسن ضبط التوقفات أو سرعة الإلقاء.",
        },
    input.teleprompterUsed
      ? {
          type: "delivery",
          severity: "neutral",
          content:
            "استخدمت التلقين أثناء التسجيل؛ راقب ثبات النظرة حتى لا يظهر الاعتماد عليه.",
        }
      : {
          type: "delivery",
          severity: "positive",
          content:
            "الأداء اعتمد على الذاكرة المباشرة، ما يزيد من صدق الاتصال بالكاميرا.",
        },
  ];

  notes.push(
    input.hadRetake
      ? {
          type: "improvement",
          severity: "neutral",
          content:
            "وجود إعادة تسجيل طبيعي، لكن حاول تثبيت نقطة البدء لتقليل عدد الإعادات.",
        }
      : {
          type: "improvement",
          severity: "positive",
          content:
            "التنفيذ جاء مستقراً من المحاولة الحالية، ويمكن البناء عليه كنسخة مرجعية جيدة.",
        }
  );

  return {
    score,
    notes,
  };
}
