"""
Migrate stable_scene_key from SHA1 to SHA256.

STATUS (2026-05-14): OUT-OF-SCOPE for current Railway production.
The directors-studio Python MVP that owns this `Scene` SQLAlchemy model is
NOT deployed to Railway. The `scenes` table in the live Railway Postgres
belongs to the Drizzle schema in `apps/backend/src/db/schema.ts` and has
NO `slugline` / `scene_text` / `stable_scene_key` columns — running this
script against it raises `UndefinedColumn` immediately.

This script is preserved for the future when:
  1. The Python MVP backend is deployed with its own Postgres instance, AND
  2. That instance contains pre-existing rows whose stable_scene_key was
     generated by the old SHA1 path in script_parser.py.

The SHA1→SHA256 fix in script_parser.py is prospective — it only affects
keys generated AFTER the change. No historical migration is needed unless
a SHA1-era dataset is actually deployed somewhere.

When that day comes:
    python migrations/migrate_stable_key_sha256.py

Idempotent — skips rows whose key already matches the new SHA256 digest.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

# Allow running from repo root or backend directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.database import SessionLocal
from app.models import Scene  # type: ignore[attr-defined]


def _sha256_key(slugline: str, scene_text: str) -> str:
    summary_source = scene_text.replace("\n", " ").strip()
    return hashlib.sha256(
        f"{slugline}|{summary_source[:120]}".encode("utf-8")
    ).hexdigest()[:20]


def run() -> None:
    db = SessionLocal()
    try:
        scenes = db.query(Scene).all()
        updated = 0
        for scene in scenes:
            new_key = _sha256_key(scene.slugline or "", scene.scene_text or "")
            if scene.stable_scene_key != new_key:
                scene.stable_scene_key = new_key
                updated += 1
        db.commit()
        print(f"Migration complete: {updated}/{len(scenes)} rows updated.")
    except Exception as exc:
        db.rollback()
        print(f"Migration failed: {exc}", file=sys.stderr)
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    run()
