import { TaskType } from "../../enums";

import type { BrainstormAgentDefinition } from "./types";

/**
 * الوحدات المتقدمة (Advanced Modules)
 */
export const ADVANCED_AGENTS: readonly BrainstormAgentDefinition[] =
  Object.freeze([
    {
      id: TaskType.CHARACTER_DEEP_ANALYZER,
      name: "PsycheScope AI",
      nameAr: "مجهر النفسية",
      role: "التحليل النفسي العميق",
      description:
        "الوحدة 3 - مجهر النفسية العميقة: محلل شخصيات متقدم يستخدم نماذج علم النفس الحاسوبي",
      category: "advanced",
      icon: "brain",
      taskType: TaskType.CHARACTER_DEEP_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.CHARACTER_NETWORK, TaskType.CHARACTER_VOICE],
      enhances: [TaskType.CHARACTER_VOICE],
      complexityScore: 0.92,
      phaseRelevance: [3],
    },
    {
      id: TaskType.DIALOGUE_ADVANCED_ANALYZER,
      name: "ConversationLens AI",
      nameAr: "عدسة المحادثة",
      role: "التحليل المتقدم للحوار",
      description:
        "الوحدة 4 - عدسة المحادثة المتقدمة: محلل حوار متطور يستخدم تقنيات اللسانيات الحاسوبية",
      category: "advanced",
      icon: "message-square",
      taskType: TaskType.DIALOGUE_ADVANCED_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.DIALOGUE_FORENSICS],
      enhances: [TaskType.CHARACTER_VOICE],
      complexityScore: 0.85,
      phaseRelevance: [3],
    },
    {
      id: TaskType.VISUAL_CINEMATIC_ANALYZER,
      name: "CinemaVision AI",
      nameAr: "بصيرة السينما",
      role: "التحليل السينمائي البصري",
      description: "الوحدة 5 - بصيرة السينما الذكية: محلل بصري سينمائي متطور",
      category: "advanced",
      icon: "film",
      taskType: TaskType.VISUAL_CINEMATIC_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: false,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.PRODUCIBILITY_ANALYZER],
      enhances: [TaskType.PRODUCIBILITY_ANALYZER],
      complexityScore: 0.8,
      phaseRelevance: [3],
    },
    {
      id: TaskType.THEMES_MESSAGES_ANALYZER,
      name: "PhilosophyMiner AI",
      nameAr: "منقّب الفلسفة",
      role: "تحليل المواضيع والرسائل",
      description: "الوحدة 6 - منقب الفلسفة العميقة: محلل موضوعات ورسائل متطور",
      category: "advanced",
      icon: "book-open",
      taskType: TaskType.THEMES_MESSAGES_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.THEMATIC_MINING,
        TaskType.CULTURAL_HISTORICAL_ANALYZER,
      ],
      enhances: [TaskType.LITERARY_QUALITY_ANALYZER],
      complexityScore: 0.95,
      phaseRelevance: [3],
    },
    {
      id: TaskType.CULTURAL_HISTORICAL_ANALYZER,
      name: "ChronoContext AI",
      nameAr: "سياق الزمن",
      role: "التحليل الثقافي التاريخي",
      description:
        "الوحدة 7 - سياق الزمن الثقافي: محلل سياق ثقافي تاريخي متطور",
      category: "advanced",
      icon: "globe",
      taskType: TaskType.CULTURAL_HISTORICAL_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.WORLD_BUILDER,
        TaskType.TARGET_AUDIENCE_ANALYZER,
      ],
      enhances: [TaskType.WORLD_BUILDER],
      complexityScore: 0.88,
      phaseRelevance: [1, 3],
    },
    {
      id: TaskType.PRODUCIBILITY_ANALYZER,
      name: "ProductionOracle AI",
      nameAr: "وحي الإنتاج",
      role: "تحليل قابلية الإنتاج",
      description: "الوحدة 8 - وحي الإنتاج الذكي: محلل قابلية إنتاج متطور",
      category: "advanced",
      icon: "chart-bar",
      taskType: TaskType.PRODUCIBILITY_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.VISUAL_CINEMATIC_ANALYZER],
      enhances: [],
      complexityScore: 0.78,
      phaseRelevance: [5],
    },
    {
      id: TaskType.TARGET_AUDIENCE_ANALYZER,
      name: "AudienceCompass AI",
      nameAr: "بوصلة الجمهور",
      role: "تحليل الجمهور المستهدف",
      description: "الوحدة 9 - بوصلة الجمهور الذكية: محلل جمهور مستهدف متطور",
      category: "advanced",
      icon: "compass",
      taskType: TaskType.TARGET_AUDIENCE_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: true,
        hasMemory: true,
        usesSelfReflection: false,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.AUDIENCE_RESONANCE,
        TaskType.CULTURAL_HISTORICAL_ANALYZER,
      ],
      enhances: [TaskType.AUDIENCE_RESONANCE],
      complexityScore: 0.82,
      phaseRelevance: [1, 5],
    },
    {
      id: TaskType.LITERARY_QUALITY_ANALYZER,
      name: "AestheticsJudge AI",
      nameAr: "قاضي الجماليات",
      role: "تحليل الجودة الأدبية",
      description: "الوحدة 10 - قاضي الجماليات الأدبية: محلل جودة أدبية متطور",
      category: "advanced",
      icon: "trophy",
      taskType: TaskType.LITERARY_QUALITY_ANALYZER,
      capabilities: {
        canAnalyze: true,
        canGenerate: false,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [
        TaskType.STYLE_FINGERPRINT,
        TaskType.THEMES_MESSAGES_ANALYZER,
      ],
      enhances: [],
      complexityScore: 0.9,
      phaseRelevance: [3, 5],
    },
    {
      id: TaskType.RECOMMENDATIONS_GENERATOR,
      name: "WisdomSynthesizer AI",
      nameAr: "مركّب الحكمة",
      role: "توليد التوصيات والتحسينات",
      description:
        "الوحدة 11 - مُركب الحكمة الإبداعية: مولد توصيات وتحسينات متطور",
      category: "advanced",
      icon: "lightbulb",
      taskType: TaskType.RECOMMENDATIONS_GENERATOR,
      capabilities: {
        canAnalyze: true,
        canGenerate: true,
        canPredict: false,
        hasMemory: true,
        usesSelfReflection: true,
        supportsRAG: true,
      },
      collaboratesWith: [TaskType.ANALYSIS, TaskType.LITERARY_QUALITY_ANALYZER],
      enhances: [],
      complexityScore: 0.88,
      phaseRelevance: [5],
    },
  ]);
