import type { NoteType, Take } from "./types";

export const RECORDING_MIME_CANDIDATES = [
  "video/webm;codecs=vp9,opus",
  "video/webm;codecs=vp8,opus",
  "video/webm",
];

export const EMPTY_CAPTIONS_TRACK = "data:text/vtt;charset=utf-8,WEBVTT%0A";

export const NOTE_TYPE_LABELS: Record<NoteType, string> = {
  emotion: "💫 عاطفة",
  delivery: "🎤 إلقاء",
  timing: "⏱️ توقيت",
  movement: "🎭 حركة",
  improvement: "💡 تحسين",
};

export const NOTE_TYPE_COLOR: Record<NoteType, string> = {
  emotion: "bg-pink-500/20 text-pink-300",
  delivery: "bg-blue-500/20 text-blue-300",
  timing: "bg-purple-500/20 text-purple-300",
  movement: "bg-orange-500/20 text-orange-300",
  improvement: "bg-cyan-500/20 text-cyan-300",
};

export const SAMPLE_SCRIPT = `المشهد الأول - غرفة المعيشة - نهاراً

تدخل سارة الغرفة بخطوات متثاقلة، تحمل في يدها رسالة مفتوحة.

سارة: (تنظر للرسالة بصدمة)
لا... هذا لا يمكن أن يكون حقيقياً.
كيف يمكنه أن يفعل هذا بعد كل هذه السنوات؟

(تجلس على الأريكة، تمسك الرسالة بيدين مرتجفتين)

سارة: (بصوت مختنق)
ظننت أننا كنا عائلة...
ظننت أن الماضي قد انتهى.

(تنهض فجأة، تمشي نحو النافذة)

سارة: (بحزم)
لكنني لن أسمح لهذا أن يدمر ما بنيته.
لقد تغيرت... وسأثبت ذلك.`;

export const SAMPLE_TAKES: Take[] = [
  {
    id: "sample-1",
    name: "Take 1 - أولي",
    duration: 125,
    recordedAt: "2025-01-15T10:30:00.000Z",
    notes: [
      {
        id: "sample-1-note-1",
        timestamp: 15,
        type: "emotion",
        content: "افتتاحية عاطفية قوية والصدمة مقروءة بصرياً.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-2",
        timestamp: 45,
        type: "timing",
        content: "يمكن إبطاء الإيقاع هنا قليلاً قبل الجملة الحاسمة.",
        severity: "needs_work",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-3",
        timestamp: 92,
        type: "movement",
        content: "الانتقال نحو النافذة يخدم التصعيد جيداً.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 78,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-2",
    name: "Take 2 - تحسين",
    duration: 132,
    recordedAt: "2025-01-15T10:45:00.000Z",
    notes: [
      {
        id: "sample-2-note-1",
        timestamp: 20,
        type: "emotion",
        content: "عمق عاطفي ممتاز في لحظة الانكسار الأولى.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-2",
        timestamp: 52,
        type: "timing",
        content: "الوقفة هنا مؤثرة ومضبوطة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-3",
        timestamp: 100,
        type: "improvement",
        content: "النهاية تحتاج طبقة حسم أكثر وضوحاً.",
        severity: "neutral",
        autoGenerated: true,
      },
    ],
    score: 85,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-3",
    name: "Take 3 - نهائي",
    duration: 128,
    recordedAt: "2025-01-15T11:00:00.000Z",
    notes: [
      {
        id: "sample-3-note-1",
        timestamp: 18,
        type: "emotion",
        content: "الصدق العاطفي حاضر من البداية حتى الخاتمة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-2",
        timestamp: 58,
        type: "delivery",
        content: "التلوين النغمي متوازن ويخدم الرهان الدرامي.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-3",
        timestamp: 96,
        type: "movement",
        content: "لغة الجسد واضحة ومنضبطة داخل الكادر.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 92,
    status: "completed",
    source: "sample",
  },
];
