import type { PersistedSelfTapeTake } from "../../lib/self-tape";

export type ActiveTool =
  | "teleprompter"
  | "recorder"
  | "comparison"
  | "notes"
  | "export";
export type CameraState = "idle" | "requesting" | "ready" | "error";
export type NotificationState = {
  type: "success" | "error" | "info";
  message: string;
} | null;
export type NoteType =
  | "emotion"
  | "delivery"
  | "timing"
  | "movement"
  | "improvement";
export type NoteSeverity = "positive" | "neutral" | "needs_work";

export interface TakeNote {
  id: string;
  timestamp: number;
  type: NoteType;
  content: string;
  severity: NoteSeverity;
  autoGenerated: boolean;
}

export interface Take extends PersistedSelfTapeTake {
  notes: TakeNote[];
  videoUrl?: string;
}

export interface TeleprompterSettings {
  speed: number;
  fontSize: number;
  mirrorMode: boolean;
  highlightCurrentLine: boolean;
  autoScroll: boolean;
  countdownSeconds: number;
}

export interface ExportSettings {
  quality: "casting" | "high" | "medium";
  format: "mp4" | "mov" | "webm";
  includeSlate: boolean;
  slateDuration: number;
  actorName: string;
  projectName: string;
  roleName: string;
  agencyName: string;
}

export interface ComparisonView {
  leftTakeId: string | null;
  rightTakeId: string | null;
  syncPlayback: boolean;
}

export interface PendingTake {
  id: string;
  name: string;
  recordedAt: string;
  mimeType: string;
  teleprompterUsed: boolean;
}

export interface SelfTapeSuiteSnapshot {
  scriptText: string;
  takes: PersistedSelfTapeTake[];
  activeTool: ActiveTool;
  teleprompterSettings: TeleprompterSettings;
  exportSettings: ExportSettings;
  comparisonView: ComparisonView;
  notesTakeId: string | null;
}
