import { readStoredSelfTapeTakes } from "../../lib/self-tape";

import { SAMPLE_TAKES } from "./constants";

import type { NoteSeverity, Take, TakeNote } from "./types";
import type { PersistedSelfTapeTake } from "../../lib/self-tape";

export function delay(milliseconds: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

export function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

export function cloneSampleTakes(): Take[] {
  return SAMPLE_TAKES.map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}

export function formatTime(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return `${minutes.toString().padStart(2, "0")}:${remainder
    .toString()
    .padStart(2, "0")}`;
}

export function formatRecordedAt(value: string): string {
  return new Date(value).toLocaleString("ar-EG", {
    hour: "2-digit",
    minute: "2-digit",
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function toPersistedTake(take: Take): PersistedSelfTapeTake {
  const { videoUrl: _videoUrl, mimeType, score, ...baseTake } = take;

  return {
    ...baseTake,
    ...(typeof mimeType === "string" ? { mimeType } : {}),
    ...(typeof score === "number" ? { score } : {}),
  };
}

export function createNotesFromInsights(
  notes: {
    type: "timing" | "delivery" | "improvement";
    severity: NoteSeverity;
    content: string;
  }[],
  duration: number
): TakeNote[] {
  const safeDuration = Math.max(duration, 1);
  const slots = Math.max(notes.length, 1);

  return notes.map((note, index) => ({
    id: `note-${Date.now()}-${index}`,
    timestamp: clamp(
      Math.round((safeDuration / slots) * (index + 0.5)),
      0,
      safeDuration
    ),
    type: note.type,
    severity: note.severity,
    content: note.content,
    autoGenerated: true,
  }));
}

export function getSeverityContainerClass(severity: NoteSeverity): string {
  switch (severity) {
    case "positive":
      return "bg-green-500/10 border-green-500/30";
    case "needs_work":
      return "bg-yellow-500/10 border-yellow-500/30";
    default:
      return "bg-black/14 border-purple-500/30";
  }
}

export function getScoreColor(score: number | undefined): string {
  if (!score) {
    return "text-white/55";
  }

  if (score >= 85) {
    return "text-green-400";
  }

  if (score >= 70) {
    return "text-yellow-400";
  }

  return "text-red-400";
}

export function loadInitialTakes(): Take[] {
  const fallback = cloneSampleTakes().map(toPersistedTake);
  return readStoredSelfTapeTakes(fallback).map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}
